import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: {
    template: "%s - Shopper online store",
    default: "Shopper online store",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="flex flex-col min-h-screen">
        <Header />
        <main className="flex-1">
          {children}
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#363636",
                color: "#fff",
              },
            }}
          />
        </main>
        <Footer />
      </div>
    </ClerkProvider>
  );
}
